- include_tasks: setup-debian.yml
  when: ansible_os_family == 'Debian'

- block:
  - name: Register postgres status
    ansible.builtin.shell: brew services info postgresql@{{ version }} --json | jq ".[].running?"
    register: postgresql_running

  - name: Start postgresql
    command: brew services start postgresql
    when: not postgresql_running | bool
  when: ansible_os_family == "Darwin"

- block:
    - name: Starting Postgres
      service:
        name: 'postgresql'
        state: 'started'
        enabled: 'yes'
  when: ansible_os_family == "Debian"

- name: Make sure psycopg2 is installed
  pip:
    name: psycopg2
    state: present
  when: ansible_os_family == 'Debian'

- name: DB user
  postgresql_user:
    login_user: "{{ lookup('env', 'USER') }}"
    db: postgres
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    role_attr_flags: SUPERUSER
    encrypted: yes
