- name: Add PostgreSQL repository key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add PostgreSQL repository
  apt_repository:
    repo: "{{ repo }}"
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install PostgreSQL server
  apt:
    name: [
      "postgresql-{{ version }}",
      "postgresql-client-{{ version }}",
      'libpq-dev'
    ]

- name: Copy PostgreSQL config
  copy:
    src: "{{ item }}"
    dest: "/etc/postgresql/{{ version }}/main/{{ item }}"
    backup: yes
  with_items:
  - pg_hba.conf
  notify: restart postgresql

- name: DB user
  become_user: postgres
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    role_attr_flags: SUPERUSER
    encrypted: yes
