---
- name: Update cache
  become: true
  apt:
    update_cache: yes

- name: Upgrade packages
  become: true
  apt:
    upgrade: full

- name: Install packages
  become: true
  apt:
    name: [
      # ruby build requirements
      'autoconf',
      'bison',
      'build-essential',
      'cmake',
      'dconf-cli',
      'gcc',
      'libffi-dev',
      'libgdbm-dev',
      'libgdbm6',
      'libncurses5-dev',
      'libreadline6-dev',
      'libsqlite3-dev',
      'libssl-dev',
      'libyaml-dev',
      'node-gyp',
      'nodejs',
      'npm',
      'patch',
      'rustc',
      'uuid-dev',
      'xclip',
      'zlib1g-dev',
      # workflow requirements
      'bat',
      'dialog',
      'dos2unix',
      'exa',
      'git',
      'gitg',
      'htop',
      'net-tools',
      'p7zip-full',
      'peco',
      'redis-server',
      's3cmd',
      'silversearcher-ag',
      'sqlite3',
      'tmux',
      'tree',
      'uchardet',
      'whois',
      'wkhtmltopdf',
      'fzf',
      'fossil',
      'zoxide',
      'zip',
      'zsh-syntax-highlighting',
      'zsh-autosuggestions'
    ]
