---
- name: Update cache
  apt:
    update_cache: yes

- name: Upgrade packages
  apt:
    upgrade: full

- name: Install packages
  apt:
    name: [
      # ruby build requirements
      'autoconf',
      'bison',
      'build-essential',
      'dconf-cli',
      'gcc-6',
      'cmake',
      'libffi-dev',
      'libgdbm-dev',
      'libgdbm5',
      'libncurses5-dev',
      'libreadline6-dev',
      'libsqlite3-dev',
      'libssl1.0-dev',
      'nodejs-dev',
      'node-gyp',
      'libyaml-dev',
      'nodejs',
      'npm',
      'xclip',
      'zlib1g-dev',
      # workflow requirements
      'autojump',
      'dialog',
      'dos2unix',
      'git',
      'gitg',
      'htop',
      'net-tools',
      'p7zip-full',
      'peco',
      'redis-server',
      's3cmd',
      'silversearcher-ag',
      'sqlite3',
      'tmux',
      'tree',
      'uchardet',
      'whois',
      'wkhtmltopdf',
      'zip',
      'zsh-syntax-highlighting',
      # Ansible plugins requirements
      'python-pexpect',
      'python-pip',
      'python-psycopg2'
    ]
