- include_tasks: setup-debian.yml
  when: ansible_os_family == 'Debian'

- name: Copy rbenv start script
  copy:
    src: rbenv.sh
    dest: ~/.rbenv.sh
    mode: 775

- name: Add rbenv start script to bashrc
  become: false
  lineinfile:
    dest: ~/.bashrc
    state: present
    regexp: 'rbenv.sh$'
    line: 'source ~/.rbenv.sh'

- name: Register rbenv root
  shell:  rbenv root
  register: rbenv_root

- name: Install selected Rubies
  ansible.builtin.command:
    cmd: "rbenv install {{ item }} -s"
    creates: "{{ rbenv_root }}/versions/{{ item }}/bin/ruby"
  loop: "{{ ruby_versions }}"

- name: Make ruby default
  command: "rbenv global {{ ruby_default }}"
  args:
    creates: "{{ rbenv_root }}/version"
