- name: Clone rbenv
  become: false
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: ~/.rbenv
    accept_hostkey: yes

- name: Compile dynamic extension to speed up rbenv
  become: false
  shell: "cd ~/.rbenv && src/configure && make -C src"

- name: Create rbenv plugins folder
  become: false
  file:
    path: ~/.rbenv/plugins
    state: directory

- name: Install RubyBuild
  become: false
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: ~/.rbenv/plugins/ruby-build
    accept_hostkey: yes
